"""empty message

Revision ID: 1da425ff296e
Revises: ebb7f0802b69
Create Date: 2019-11-06 11:28:41.822126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da425ff296e'
down_revision = 'ebb7f0802b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_Lenta', sa.String(), nullable=True),
    sa.Column('date_Lenta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lenta')
    # ### end Alembic commands ###
