"""empty message

Revision ID: 2670b287899e
Revises: f0b7eadc60c7
Create Date: 2019-11-08 14:13:19.213261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2670b287899e'
down_revision = 'f0b7eadc60c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perekrestok')
    op.drop_table('lenta')
    op.drop_index('ix_sku_sku_lowercase', table_name='sku')
    op.drop_table('sku')
    op.drop_table('pka')
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_news', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_news', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_pkey')
    )
    op.create_table('pka',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_pka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_pka', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pka_pkey')
    )
    op.create_table('sku',
    sa.Column('id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('sku_category', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku_html_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sku_html_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sku_html_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sku_twin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sku_lowercase', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sku_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sku_discount_desc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku_price_asc', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('sku_price_desc', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sku_pkey')
    )
    op.create_index('ix_sku_sku_lowercase', 'sku', ['sku_lowercase'], unique=False)
    op.create_table('lenta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_lenta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('html_lenta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lenta_pkey')
    )
    op.create_table('perekrestok',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_perekrestok', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_perekrestok', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='perekrestok_pkey')
    )
    # ### end Alembic commands ###
