"""empty message

Revision ID: 2f1623d0bd16
Revises: 51f666235aa6
Create Date: 2019-11-06 12:52:25.706518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1623d0bd16'
down_revision = '51f666235aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perekrestok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_perekrestok', sa.String(), nullable=True),
    sa.Column('date_perekrestok', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_pka', sa.String(), nullable=True),
    sa.Column('date_pka', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pka')
    op.drop_table('perekrestok')
    # ### end Alembic commands ###
