"""empty message

Revision ID: 30cfb474f3e2
Revises: 8319924a97fd
Create Date: 2019-11-07 14:38:54.853917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cfb474f3e2'
down_revision = '8319924a97fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'sku_price_desc')
    op.drop_column('sku', 'sku_type')
    op.drop_column('sku', 'sku_price_asc')
    op.drop_column('sku', 'sku_discount_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_discount_desc', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_asc', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_type', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_desc', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
