"""empty message

Revision ID: 382323375b0a
Revises: 9e9c77791006
Create Date: 2019-11-07 14:48:27.193599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382323375b0a'
down_revision = '9e9c77791006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'sku_price_desc')
    op.drop_column('sku', 'sku_price_asc')
    op.drop_column('sku', 'sku_discount_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_discount_desc', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_asc', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_desc', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
