"""empty message

Revision ID: 3f0c2d70242e
Revises: 9cf5b5519bb0
Create Date: 2020-01-20 10:06:17.308383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0c2d70242e'
down_revision = '9cf5b5519bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visit_time')
    # ### end Alembic commands ###
