"""empty message

Revision ID: 51f666235aa6
Revises: 1da425ff296e
Create Date: 2019-11-06 11:49:48.928300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51f666235aa6'
down_revision = '1da425ff296e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lenta', sa.Column('date_lenta', sa.DateTime(), nullable=True))
    op.add_column('lenta', sa.Column('html_lenta', sa.String(), nullable=True))
    op.drop_column('lenta', 'html_Lenta')
    op.drop_column('lenta', 'date_Lenta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lenta', sa.Column('date_Lenta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lenta', sa.Column('html_Lenta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lenta', 'html_lenta')
    op.drop_column('lenta', 'date_lenta')
    # ### end Alembic commands ###
