"""empty message

Revision ID: 5f3e83fe6f8f
Revises: 9d6d3a00e4fa
Create Date: 2020-01-15 11:25:49.742145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3e83fe6f8f'
down_revision = '9d6d3a00e4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_status')
    # ### end Alembic commands ###
