"""empty message

Revision ID: 625ada6a12fa
Revises: 264eab67f6ec
Create Date: 2019-11-06 15:28:23.809902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625ada6a12fa'
down_revision = '264eab67f6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sku_sku_lowercase', table_name='sku')
    op.drop_column('sku', 'sku_name')
    op.drop_column('sku', 'sku_lowercase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_lowercase', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_sku_sku_lowercase', 'sku', ['sku_lowercase'], unique=False)
    # ### end Alembic commands ###
