"""empty message

Revision ID: 6f278739b6f5
Revises: 2670b287899e
Create Date: 2019-11-08 14:14:21.298262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f278739b6f5'
down_revision = '2670b287899e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_lenta', sa.String(), nullable=True),
    sa.Column('date_lenta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_news', sa.String(), nullable=True),
    sa.Column('date_news', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perekrestok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_perekrestok', sa.String(), nullable=True),
    sa.Column('date_perekrestok', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_pka', sa.String(), nullable=True),
    sa.Column('date_pka', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('sku_category', sa.Integer(), nullable=True),
    sa.Column('sku_name', sa.String(length=200), nullable=True),
    sa.Column('sku_lowercase', sa.String(length=200), nullable=True),
    sa.Column('sku_price_asc', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sku_price_desc', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sku_discount_desc', sa.Integer(), nullable=True),
    sa.Column('sku_html_1', sa.String(), nullable=True),
    sa.Column('sku_html_2', sa.String(), nullable=True),
    sa.Column('sku_html_3', sa.String(), nullable=True),
    sa.Column('sku_twin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_sku_lowercase'), 'sku', ['sku_lowercase'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_sku_lowercase'), table_name='sku')
    op.drop_table('sku')
    op.drop_table('pka')
    op.drop_table('perekrestok')
    op.drop_table('news')
    op.drop_table('lenta')
    # ### end Alembic commands ###
