"""empty message

Revision ID: 8319924a97fd
Revises: 625ada6a12fa
Create Date: 2019-11-06 15:28:45.101095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8319924a97fd'
down_revision = '625ada6a12fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_lowercase', sa.String(length=200), nullable=True))
    op.add_column('sku', sa.Column('sku_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_sku_sku_lowercase'), 'sku', ['sku_lowercase'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_sku_lowercase'), table_name='sku')
    op.drop_column('sku', 'sku_name')
    op.drop_column('sku', 'sku_lowercase')
    # ### end Alembic commands ###
