"""empty message

Revision ID: 90631c57e85b
Revises: 382323375b0a
Create Date: 2019-11-07 14:48:45.604551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90631c57e85b'
down_revision = '382323375b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_discount_desc', sa.Integer(), nullable=True))
    op.add_column('sku', sa.Column('sku_price_asc', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('sku', sa.Column('sku_price_desc', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'sku_price_desc')
    op.drop_column('sku', 'sku_price_asc')
    op.drop_column('sku', 'sku_discount_desc')
    # ### end Alembic commands ###
