"""empty message

Revision ID: 912d014ca8d7
Revises: bd2c238a9630
Create Date: 2019-11-06 15:26:03.752747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912d014ca8d7'
down_revision = 'bd2c238a9630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'sku_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
