"""empty message

Revision ID: 9cf5b5519bb0
Revises: ee580a3a6563
Create Date: 2020-01-15 15:50:24.669675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf5b5519bb0'
down_revision = 'ee580a3a6563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('heart_productsId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
