"""empty message

Revision ID: 9d6d3a00e4fa
Revises: f582751be238
Create Date: 2019-11-13 16:49:37.945252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d6d3a00e4fa'
down_revision = 'f582751be238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lenta')
    op.drop_table('perekrestok')
    op.drop_table('pka')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pka',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_pka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_pka', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pka_pkey')
    )
    op.create_table('perekrestok',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_perekrestok', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_perekrestok', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='perekrestok_pkey')
    )
    op.create_table('lenta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('html_lenta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_lenta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lenta_pkey')
    )
    # ### end Alembic commands ###
