"""empty message

Revision ID: 9e9c77791006
Revises: 30cfb474f3e2
Create Date: 2019-11-07 14:46:48.093728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9c77791006'
down_revision = '30cfb474f3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_lowercase', sa.String(length=200), nullable=True))
    op.add_column('sku', sa.Column('sku_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_sku_sku_lowercase'), 'sku', ['sku_lowercase'], unique=False)
    op.drop_column('sku', 'sku_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_type', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sku_sku_lowercase'), table_name='sku')
    op.drop_column('sku', 'sku_name')
    op.drop_column('sku', 'sku_lowercase')
    # ### end Alembic commands ###
