"""empty message

Revision ID: ebb7f0802b69
Revises: 
Create Date: 2019-11-05 15:19:37.814842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb7f0802b69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_news', sa.String(), nullable=True),
    sa.Column('date_news', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('sku_category', sa.Integer(), nullable=True),
    sa.Column('sku_name', sa.String(length=100), nullable=True),
    sa.Column('sku_lowercase', sa.String(length=100), nullable=True),
    sa.Column('sku_price_asc', sa.Integer(), nullable=True),
    sa.Column('sku_price_desc', sa.Integer(), nullable=True),
    sa.Column('sku_discount_desc', sa.Integer(), nullable=True),
    sa.Column('sku_html_1', sa.String(), nullable=True),
    sa.Column('sku_html_2', sa.String(), nullable=True),
    sa.Column('sku_html_3', sa.String(), nullable=True),
    sa.Column('sku_type', sa.String(length=5), nullable=True),
    sa.Column('sku_twin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_sku_lowercase'), 'sku', ['sku_lowercase'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sku_sku_lowercase'), table_name='sku')
    op.drop_table('sku')
    op.drop_table('news')
    # ### end Alembic commands ###
