"""empty message

Revision ID: ee580a3a6563
Revises: 42701bee5674
Create Date: 2020-01-15 11:38:55.766527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee580a3a6563'
down_revision = '42701bee5674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_status', sa.Column('status', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_status', 'status')
    # ### end Alembic commands ###
