"""empty message

Revision ID: f2367af2f0d9
Revises: 2c87f17cdf37
Create Date: 2019-11-06 14:08:46.308412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2367af2f0d9'
down_revision = '2c87f17cdf37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sku_sku_lowercase', table_name='sku')
    op.drop_column('sku', 'sku_lowercase')
    op.drop_column('sku', 'sku_category')
    op.drop_column('sku', 'sku_price_asc')
    op.drop_column('sku', 'sku_html_1')
    op.drop_column('sku', 'sku_price_desc')
    op.drop_column('sku', 'sku_html_3')
    op.drop_column('sku', 'sku_twin')
    op.drop_column('sku', 'sku_name')
    op.drop_column('sku', 'sku_type')
    op.drop_column('sku', 'sku_discount_desc')
    op.drop_column('sku', 'sku_html_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('sku_html_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_discount_desc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_twin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_html_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_desc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_html_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_price_asc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sku', sa.Column('sku_lowercase', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_sku_sku_lowercase', 'sku', ['sku_lowercase'], unique=False)
    # ### end Alembic commands ###
